name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TAG_NAME: V1.0.0

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mushroomgead/clone-smart-saving:$TAG_NAME

    - name: Push the Docker image
      run: docker push mushroomgead/clone-smart-saving:$TAG_NAME
